export const AUDIT_ACTIONS = [
  'LOGIN',
  'LOGIN_FAIL',
  'LOGOUT',
  'REFRESH',
  'USER_CREATED',
  'PATIENT_CREATED',
  'PATIENT_UPDATED',
  'FORM_CREATED',
  'FORM_UPDATED',
  'FORM_DEACTIVATED',
  'FORM_PUBLISHED',
  'FORM_SUBMITTED',
  'ASSESSMENT_CREATED',
  'NOTIFICATION_READ',
  'NOTIFICATION_DONE',
  'HIGH_RISK_ALERT_CREATED',
  'PASSWORD_RESET_BY_ADMIN',
  'USER_ACTIVATED',
  'USER_DEACTIVATED',
  'USER_PROFILE_UPDATED',
  'PASSWORD_CHANGED',
  'PASSWORD_RESET_REQUESTED',
  'PASSWORD_RESET_COMPLETED',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const STRICT_AUDIT_ACTIONS: ReadonlySet<AuditAction> = new Set([
  'LOGIN',
  'LOGIN_FAIL',
  'USER_CREATED',
  'PATIENT_CREATED',
  'PASSWORD_RESET_BY_ADMIN',
  'PASSWORD_CHANGED',
  'PASSWORD_RESET_COMPLETED',
  'HIGH_RISK_ALERT_CREATED',
]);

export function isStrictAuditAction(a: AuditAction): boolean {
  return STRICT_AUDIT_ACTIONS.has(a);
}
