-- Enforce at most one ACTIVE (PENDING or APPROVED) service request per
-- (service, patient) at the database level.
--
-- This closes the read-then-insert race in createRequest: two concurrent
-- requests by the same patient for the same service could both pass the
-- application-level duplicate check and insert two PENDING rows, each of which
-- could later be approved and consume a separate seat for one patient.
--
-- Prisma cannot express a partial (filtered) unique index in schema.prisma, so
-- this lives as raw SQL. IT MUST BE PRESERVED — do not let an autogenerated
-- migration drop it. The application maps the resulting unique violation (P2002)
-- to the DUPLICATE_SERVICE_REQUEST error.
CREATE UNIQUE INDEX "ServiceRequest_active_unique"
  ON "ServiceRequest" ("serviceId", "patientId")
  WHERE "status" IN ('PENDING', 'APPROVED');
