name: bahya_l10n
description: Generated localization package for the Bahya application.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
